"""
backend/exporter.py
-------------------
Builds a formatted Excel workbook with one sheet per FCA tab.
Columns: Description | Code | YE24 | YE25 | Difference | % Movement | Remarks

AI remarks are generated by Kimi for any row with |% movement| >= REMARK_THRESHOLD
or priority == High.
"""

import io
import math
import json
import httpx
import os
from dotenv import load_dotenv

load_dotenv()

try:
    import xlsxwriter
except ImportError:
    xlsxwriter = None

BASE_URL = os.getenv("LLM_BASE_URL", "https://nova.deloitte.com.cn/del/v1")
API_KEY  = os.getenv("LLM_API_KEY", "")
MODEL    = os.getenv("LLM_MODEL", "Kimi-K2.5")

# Rows with |pct_change| above this threshold get an AI remark
REMARK_THRESHOLD = 20.0   # %


# ── AI remark generation ───────────────────────────────────────────────────

REMARK_SYSTEM = (
    "You are a senior actuary writing a one-sentence remark for an actuarial review memo "
    "of HKIA FCA regulatory returns. "
    "The remark should identify the most likely business driver behind the movement. "
    "Be specific and professional. Maximum 25 words. No bullet points."
)


def _stream_remark(description: str, code: str, ye24: float, ye25: float,
                   diff: float, pct: float, tab: str) -> str:
    """Call Kimi and return a one-sentence remark for this line item."""
    sign = "increase" if diff > 0 else "decrease"
    user_msg = (
        f"Tab: {tab}\n"
        f"Account: {description} ({code})\n"
        f"YE24: {ye24:,.0f}   YE25: {ye25:,.0f}\n"
        f"Movement: {diff:,.0f} ({pct:+.1f}%) — {sign}\n\n"
        "Write one sentence explaining the likely business driver of this movement."
    )

    url = BASE_URL.rstrip("/") + "/chat/completions"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": REMARK_SYSTEM},
            {"role": "user",   "content": user_msg},
        ],
        "max_tokens": 80,
        "stream": True,
    }

    collected = []
    try:
        with httpx.Client(verify=False, timeout=60) as client:
            with client.stream("POST", url, headers=headers, json=payload) as resp:
                for line in resp.iter_lines():
                    line = line.strip()
                    if not line or not line.startswith("data:"):
                        continue
                    chunk_str = line[len("data:"):].strip()
                    if chunk_str == "[DONE]":
                        break
                    try:
                        chunk = json.loads(chunk_str)
                        content = chunk["choices"][0]["delta"].get("content") or ""
                        if content:
                            collected.append(content)
                    except Exception:
                        continue
        return "".join(collected).strip()
    except Exception as e:
        return f"[Unavailable: {e}]"


def _safe_float(val) -> float | None:
    """Convert a value to float, returning None if not possible."""
    if val is None:
        return None
    try:
        f = float(val)
        return None if (math.isnan(f) or math.isinf(f)) else f
    except (TypeError, ValueError):
        return None


# ── Excel builder ──────────────────────────────────────────────────────────

def build_excel(results: list, use_ai_remarks: bool = True) -> bytes:
    """
    Build an Excel workbook from the comparison results.

    Parameters
    ----------
    results : list of { "tab": str, "data": list[dict] }
    use_ai_remarks : if False, remarks column is left blank (faster)

    Returns
    -------
    bytes  — the .xlsx file content ready for download
    """
    if xlsxwriter is None:
        raise RuntimeError("xlsxwriter is not installed. Run: pip install xlsxwriter")

    buf = io.BytesIO()
    wb  = xlsxwriter.Workbook(buf, {"in_memory": True})

    # ── Define formats ─────────────────────────────────────────────────────
    hdr = wb.add_format({
        "bold": True, "bg_color": "#1F3864", "font_color": "#FFFFFF",
        "border": 1, "align": "center", "valign": "vcenter",
        "text_wrap": True,
    })
    label = wb.add_format({
        "bold": True, "bg_color": "#D6E4F0", "border": 1,
        "valign": "vcenter", "text_wrap": True,
    })
    num_fmt  = wb.add_format({"num_format": "#,##0", "border": 1, "align": "right"})
    pct_fmt  = wb.add_format({"num_format": "0.0%",  "border": 1, "align": "right"})
    text_fmt = wb.add_format({"border": 1, "valign": "vcenter", "text_wrap": True})

    # Coloured number formats for movement columns
    pos_num  = wb.add_format({"num_format": "#,##0",  "border": 1, "align": "right",
                               "font_color": "#1E6823"})
    neg_num  = wb.add_format({"num_format": "#,##0",  "border": 1, "align": "right",
                               "font_color": "#9C0006"})
    pos_pct  = wb.add_format({"num_format": "0.0%",   "border": 1, "align": "right",
                               "font_color": "#1E6823"})
    neg_pct  = wb.add_format({"num_format": "0.0%",   "border": 1, "align": "right",
                               "font_color": "#9C0006"})

    # Row highlight formats for High / Medium priority
    hi_bg    = wb.add_format({"bg_color": "#FFCCCC", "border": 1, "valign": "vcenter",
                               "text_wrap": True})
    med_bg   = wb.add_format({"bg_color": "#FFF3CC", "border": 1, "valign": "vcenter",
                               "text_wrap": True})
    hi_num   = wb.add_format({"bg_color": "#FFCCCC", "num_format": "#,##0",
                               "border": 1, "align": "right"})
    med_num  = wb.add_format({"bg_color": "#FFF3CC", "num_format": "#,##0",
                               "border": 1, "align": "right"})
    hi_pct   = wb.add_format({"bg_color": "#FFCCCC", "num_format": "0.0%",
                               "border": 1, "align": "right"})
    med_pct  = wb.add_format({"bg_color": "#FFF3CC", "num_format": "0.0%",
                               "border": 1, "align": "right"})

    dash_fmt = wb.add_format({"border": 1, "align": "center", "font_color": "#999999"})

    COLS = ["Description", "Code", "YE24", "YE25", "Difference", "% Movement", "Remarks"]
    COL_WIDTHS = [45, 10, 18, 18, 18, 14, 55]

    for tab_result in results:
        tab_name = tab_result["tab"]
        rows     = tab_result["data"]

        # Sheet name max 31 chars, no special chars
        safe_name = tab_name[:31].replace("/", "-").replace("\\", "-").replace("?", "").replace("*", "").replace("[", "").replace("]", "")
        ws = wb.add_worksheet(safe_name)

        # Column widths
        for i, w in enumerate(COL_WIDTHS):
            ws.set_column(i, i, w)

        # Header row
        ws.set_row(0, 30)
        for i, col in enumerate(COLS):
            ws.write(0, i, col, hdr)

        ws.freeze_panes(1, 0)

        row_idx = 1
        for item in rows:
            desc    = item.get("description") or ""
            code    = item.get("cy_code") or item.get("py_code") or ""
            ye24    = _safe_float(item.get("py_value"))
            ye25    = _safe_float(item.get("cy_value"))
            diff    = _safe_float(item.get("abs_movement"))
            pct_raw = _safe_float(item.get("pct_change"))
            pct_dec = (pct_raw / 100) if pct_raw is not None else None
            priority = item.get("priority", "Low")

            # Decide background based on priority
            if priority == "High":
                tf, nf, pf = hi_bg, hi_num, hi_pct
            elif priority == "Medium":
                tf, nf, pf = med_bg, med_num, med_pct
            else:
                tf, nf, pf = text_fmt, num_fmt, pct_fmt

            ws.set_row(row_idx, 15)
            ws.write(row_idx, 0, desc, tf if priority != "Low" else label)
            ws.write(row_idx, 1, code, tf)

            # YE24
            if ye24 is not None:
                ws.write_number(row_idx, 2, ye24, nf)
            else:
                ws.write(row_idx, 2, "—", dash_fmt)

            # YE25
            if ye25 is not None:
                ws.write_number(row_idx, 3, ye25, nf)
            else:
                ws.write(row_idx, 3, "—", dash_fmt)

            # Difference — green if positive, red if negative
            if diff is not None:
                d_fmt = (pos_num if diff >= 0 else neg_num)
                if priority != "Low":
                    d_fmt = nf
                ws.write_number(row_idx, 4, diff, d_fmt)
            else:
                ws.write(row_idx, 4, "—", dash_fmt)

            # % Movement
            if pct_dec is not None:
                p_fmt = (pos_pct if pct_dec >= 0 else neg_pct)
                if priority != "Low":
                    p_fmt = pf
                ws.write_number(row_idx, 5, pct_dec, p_fmt)
            else:
                ws.write(row_idx, 5, "—", dash_fmt)

            # Remarks — AI-generated for significant movers
            remark = ""
            if use_ai_remarks and pct_raw is not None and ye24 is not None and ye25 is not None:
                if abs(pct_raw) >= REMARK_THRESHOLD or priority == "High":
                    remark = _stream_remark(
                        desc, code,
                        ye24, ye25, diff or 0, pct_raw,
                        tab_name
                    )
            ws.write(row_idx, 6, remark, tf)

            row_idx += 1

    wb.close()
    buf.seek(0)
    return buf.read()